"""initial schema

Revision ID: 791c0c98bb97
Revises: 
Create Date: 2026-07-26 23:31:23.489531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '791c0c98bb97'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('node_public_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.String(length=64), nullable=False),
    sa.Column('rsa_public_key_pem', sa.Text(), nullable=False),
    sa.Column('registered_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('node_public_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_node_public_keys_node_id'), ['node_id'], unique=True)

    op.create_table('task_encryption_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tid', sa.String(length=64), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('encrypted_dek_b64', sa.Text(), nullable=False),
    sa.Column('iv_b64', sa.String(length=64), nullable=False),
    sa.Column('target_node_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_encryption_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_encryption_keys_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_encryption_keys_tid'), ['tid'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('deployments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('pid', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('api_key', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deployments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deployments_api_key'), ['api_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployments_pid'), ['pid'], unique=True)
        batch_op.create_index(batch_op.f('ix_deployments_user_id'), ['user_id'], unique=False)

    op.create_table('user_api_rel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('api_key', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_api_rel')
    with op.batch_alter_table('deployments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deployments_user_id'))
        batch_op.drop_index(batch_op.f('ix_deployments_pid'))
        batch_op.drop_index(batch_op.f('ix_deployments_api_key'))

    op.drop_table('deployments')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    with op.batch_alter_table('task_encryption_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_encryption_keys_tid'))
        batch_op.drop_index(batch_op.f('ix_task_encryption_keys_job_id'))

    op.drop_table('task_encryption_keys')
    with op.batch_alter_table('node_public_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_node_public_keys_node_id'))

    op.drop_table('node_public_keys')
    # ### end Alembic commands ###
